version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/reto_angela
      - CONFIG_BASE_ENDPOINT=http://localhost:8080
      - CONFIG_UPLOADS_PATH=/uploads
    volumes:
      - ./uploads:/uploads
    restart: on-failure

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
